spring:
  application:
    name: medilab-department-service
  cloud:
    config:
      uri:
      - http://localhost:8888
  config:
    import:
    - configserver:http://localhost:8888
    


 


    