spring:
  application:
    name: medilab-doctor-service
  cloud:
    config:
      uri:
      - http://localhost:8888
  config:
    import:
    - configserver:http://localhost:8888
  rabbitmq:
    host: snake.rmq2.cloudamqp.com
    virtual-host: etemmzqb
    username: etemmzqb
    password: Ga8j__in_8bAyqy-Gj1HObwQGTFPEDfX
    
management:
  endpoints:
    web:
      exposure:
        include: true
        